= K101 - Nodejs-Express
:author: Hafid Haddouti
:toc: left
:toclevels: 4

Kabanero 101 - nodejs-express example used for workshops

toc::[]

== Overview

== Steps

For any step exists an own git tag.

=== Prerequisites

.Add Kabanero repo
----
$ appsody repo add kabanero https://github.com/kabanero-io/collections/releases/download/0.2.1/kabanero-index.yaml

$ appsody list kabanero
----


=== step_00: Init

Initial the project.

* Create the project using the `nodejs-express` stack from Kabanero Collection
* Run the application
* Call link:http://localhost:3000/[]
* Stop the app/container with `STRG+C` in the terminal

.Create project structure
----
$ mkdir k101-nodejs-express & cd k101-nodejs-express
$ appsody init kabanero/nodejs-express
----

.Start the app
----
$ appsody run -v

...
[Container] App started on PORT 3000
----

=== step_01: Code changes

Change the code and see immediately the modification online.

* Start the app
* modify the `app.js` and add a new endpoint
* Call the new endpoint link:http://localhost:3000/echo/test-user[]
* Stop the app/container with `STRG+C` in the terminal

.Start the app
----
$ appsody run -v

...
[Container] App started on PORT 3000
----

.Add new endpoint with random delay in processing
[source,javascript]
----
const sleep = (waitTimeInMs) => new Promise(resolve => setTimeout(resolve, waitTimeInMs));

app.get('/echo/:val', (req, res) => {
  let val = req.params.val;

  let delay = Math.floor(1000 * (Math.random() * 5)); 
  sleep(delay).then(() => {
    res.send("Echo: " + val + "; delay=" + delay);
  })
  
});
----

Verify the terminal with the Appsody log output to see the monitored file change. Appsody restarts the node process with the latest change.

.Appsody log output
----
[Container] [ControllerDebug] File watch event detected for:  FILE "app.js" WRITE [/project/user-app/app.js]
...
[Container] [ControllerDebug] New process created with pid 57
[Container]
[Container] > nodejs-express@0.2.8 start /project
[Container] > node server.js

----

Verify also that the same docker container is still running

.Check docker process
----
$ docker ps | grep k101-nodejs-express

ab14a8692277        kabanero/nodejs-express:0.2   "/.appsody/appsody-c…"   7 minutes ago       Up 7 minutes        0.0.0.0:3000->3000/tcp, 0.0.0.0:8080->8080/tcp, 0.0.0.0:9229->9229/tcp   k101-nodejs-express-dev
----

.Check the log from the docker process (similar to the log output from Appsody terminal)
----
$ docker logs -f $(docker ps | grep k101-nodejs-express | awk '{print $1}')
----

.Summary
* Fast ramp-up. New nodejs-express created without taking care about project initialization, structure, dependencies
* Undisturbed development without (manual) server restarts
* Container support out of the box, without touching Dockerfile or Docker commands

=== step_02: Codewind integration

Integrate in Codewind and test and debug the flow including monitoring and performance.

.Prerequisites
* VSCode with Codewind plugin, use the marketplace and search for `Codewind`
* Consider that the project must be located under `$HOME/codewind-workspace`

.Steps
* Add the existing project to Codewind. In Codewind view, select *Projects* > *Add Existing Project* and select the directory with our project
* Open App: use the context menu in Codewind for the project, to open app in browser
* Open Shell: to get a shell into the container
* Show all logs: to get all logs from the container in the VSCode output view
* Open Application Monitor: to open in the browser the monitor page
* Open Performance Dashboard: to open the performance page
* Create test case
** Edit load run settings
*** Path: `/echo/pf1`
*** Save
** Run Load Test
*** set a name and execute the test. repeat this multiple times
** Observe the Application Monitor
* Restart the app in Debug Mode: Select in Codewind view `Restart in Debug Mode` (consider the status bar color of VSCode: orange for debug mode)
** Set a break point in `app.js`
** Open App: because after restarting is a new port exposed
** Make a request `/echo/debug`
** Go line by line in VSCode Debug perspective, observe and watch variables
** Restart in Run Mode

.Summary
* Project provides out of the box multiple features like: Application Monitoring, Performance testing...all without explicitly configuration
* IDE integration in VSCode is helpful and hides any Appsody commands
* Debugging also out of the box supported

HINT: The features like Application Monitoring and Performance test support is dependent from the used Appsody stack. Currently not all stacks support this features.

== License

This article is licensed under the Apache License, Version 2.
Separate third-party code objects invoked within this code pattern are licensed by their respective providers pursuant
to their own separate licenses. Contributions are subject to the
link:https://developercertificate.org/[Developer Certificate of Origin, Version 1.1] and the
link:https://www.apache.org/licenses/LICENSE-2.0.txt[Apache License, Version 2].

See also link:https://www.apache.org/foundation/license-faq.html#WhatDoesItMEAN[Apache License FAQ]
.